blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/PiscesGameDev/Pisces.Client.Unity#readme
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/PiscesGameDev/Pisces.Client.Unity/discussions
    about: Ask questions and discuss with the community
